### ISSUE TITLE
what is the difference between the ping tracker source?

### ISSUE THREAD

**Issue by rosario1510** [karashiiro/PingPlugin#50]
whats the difference between com/win32 api/game packet?
i tried all of them but all of them give a different ping
the game packet specifically has a much higher ping
which one is the most accurate?

also is there any difference if i use server bar display?

**Comment by karashiiro** [comment]
They each use different tracking methods, and same of them don't work on all systems, which is why they're all offered. I don't know for sure which one is more accurate, but I think it's the Win32 one, since it seems to have the least overhead.

Using the server bar display won't make any difference.
